project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
    navigate: true
  render:
    - "*.qmd"

website:
  title: "PSYC3470"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://psyteachr.github.io/ads-v1/index.html
        text: Textbook
  sidebar:
      style: "floating"
      collapse-level: 2
      align: left
      contents: auto

format:
  html:
    theme: minty
    css: [css/nav.css,css/styles.css]
    toc: true
    include-in-header: "css/fontawesome.html"

editor: source

