---
title: "Syllabus"
editor: visual
format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
---

# PSYC 3470/SOCY 3507: Data Analytics and Data Visualization in the Social and Behavioral Sciences

::: callout-important
## Under construction

This syllabus is under construction until Spring 2023
:::

Spring 2023

Section: PSYC 3470: 30351, SOCY 3507: 46070

Time: 11:00am - 12:15pm, Monday and Wednesday

Location: James 4607

Office Hours: TBA (zoom link posted on Blackboard)

Instructor: [Dr. Matthew Crump](https://www.brooklyn.cuny.edu/web/academics/faculty/faculty_profile.jsp?faculty=1059)

Email: mcrump\@brooklyn.cuny.edu (please put ''Psyc 3470' in subject line)

## Course Description

PSYC 3470: Data Analytics and Data Visualization in the Social and Behavioral Sciences

3 hours; 3 credits

**Catalogue Description**: How the "data revolution" has transformed the way we understand and interact with the world around us. Fundamental concepts and practical techniques and skills needed for data analytics and data visualization. Availability of large datasets and their use across a variety of settings, including social networks, libraries, governments, non-profits, etc. The emergence of practices with regard to data analysis and visual communication in the social and behavioral sciences. This course is the same as Sociology 3507.

### Learning Goals/Outcomes

Students will:

-   Develop familiarity and basic competency with concepts and techniques for data analytics and visualization

    -   Outcome: students will create and contribute to a weekly learning blog to practice and demonstrate their skill-acquisition process

-   Develop competencies in data structures, importing, filtering, wrangling, and curation techniques necessary for analysis and visualization

    -   Outcomes: competencies assessed and demonstrated in weekly assignments

-   Understand principles of automation and reproducibility and learn how to produce and communicate computationally reproducible data analysis projects

    -   Outcomes: students create final project website and deliver a class presentation about their final research project.

-   Understand and critically reflect upon data usage practices in society

    -   Outcomes: demonstrated in class room discussions and reflections on readings.

## Course Materials and Textbook

All of the course materials will be available in a timely fashion on this course website and/or posted on blackboard.

Link to the course website: <https://crumplab.com/psyc3470>

### Textbook

"**Applied Data Skills**: Processing & Presenting Data" (2023) Emily Nordmann and Lisa DeBruine.

<https://psyteachr.github.io/ads-v2>

The textbook is a free and open-source web book. There are many additional free resources for learning R that will be discussed and made available throughout the semester.

## Course Structure

There are 15 weeks. This is an **in-person** class, and students are expected to participate in all aspects of the class. This is a class that involves learning computer programming skills for data-visualization and analysis. The assumption is that students may possess no prior skills in this area, so the course has an applied training component. Class time will involve mixtures of activities, including lectures, group-work, applied coding activities, presentations, and discussions.

## Course Schedule

```{r, message=FALSE, warning=FALSE, echo=FALSE, eval=TRUE}

Lectures <- rio::import("schedule.csv")
knitr::kable(Lectures)

```

## Portfolio development

Throughout this course you will learn how to analyse and communicate data using reproducible computational methods. These methods allow you to communicate information in many formats including websites, interactive web apps, slide decks, pdfs, word documents, books, web-books, and more. Students can use these very same methods to create their own personal websites, which can be used as a digital portfolio to showcase examples of their work and demonstrate their skills. To support digital portfolio development, students will learn to create a personal website and blog. Students will add content to their websites in the form of blogs and other weekly assignment content prompts. By the end of the course students will have created evidence of their learning process in the form of their course website and blog. Students can choose to share their coursework publicly or privately. For more information on see [notes on privacy and sharing in the compendium](compendium/privacy.qmd).

## Assignments and Grading

This is an engagement and skills-acquisition based course. At the beginning of the course and throughout, students will be given instruction on building and maintaining a website using quarto and github pages. Each week students will contribute blog posts and other content to their websites in response to module assignments. Students will be expected to submit URL links to their blogs using Blackboard. Students are expected to attend and participate in each class. The final project includes conducting, communicating, and preserving a reproducible data analysis project.

### Points and letter grades

| Assignment          | Points | Total |
|:--------------------|-------:|------:|
| Course blog/website |      5 |     5 |
| Weekly Blog post    |      4 |    60 |
| Attendance          |      1 |    15 |
| Midterm project     |     10 |    10 |
| Final Project       |     10 |    10 |
|                     |        |   100 |

Percentage grades are converted to letter grades according to the following rubric.

| Letter grade | Range       |
|:-------------|:------------|
| A+           | 96.67-100   |
| A            | 93.33-96.66 |
| A-           | 90-93.32    |
| B+           | 86.67-89.99 |
| B            | 83.33-86.66 |
| B-           | 80-83.32    |
| C+           | 76.67-79.99 |
| C            | 73-76.66    |
| C-           | 70-72.99    |
| D+           | 66.67-69.99 |
| D            | 63.33-66.66 |
| D-           | 60-63.32    |
| F            | 0-59.99     |

## Attendance

Students are expected to attend and participate in each class.

## Course Policies

### Due dates

Due dates are suggestions for completing coursework on a weekly basis. You may be able to work ahead, but you are not encouraged to fall behind.

You should email me if you have an exceptional circumstance preventing you from taking an assessment during an assessment week.

### Changes to the syllabus

The syllabus may be updated for clarity or to make adjustments for pedagogical purposes. The most current version of the syllabus is always available from the course website.

### Missing an Exam

In the event of an emergency, contact me as soon as possible. If you are missing an exam for religious reasons refer to the state law regarding non-attendance because of religious beliefs noted in the front matter of the Undergraduate Bulletin and Graduate Bulletin. These may be found on the Academic Calendars, Course Schedules, and Bulletins page of the Registrar's website. See also the student bereavement policy at <http://www.brooklyn.cuny.edu/web/about/initiatives/policies/bereavement.php>.

------------------------------------------------------------------------

### Accessibility

In order to receive disability-related academic accommodations students must first be registered with the Center for Student Disability Services. Students who have a documented disability or suspect they may have a disability are invited to set up an appointment with the Director of the Center for Student Disability Services, at 718-951-5538. If you have already registered with the Center for Student Disability Services, please provide your professor with the course accommodation form and discuss your specific accommodation with him/her.

------------------------------------------------------------------------

### Email Correspondence

I will regularly use e-mail via blackboard to send out announcements, changes in the syllabus, reminders about tests or due dates etc. It is your responsibility to check e-mail regularly to keep up-to-date with these announcements. I will use the e-mail address you have listed with the College. Therefore, please make sure that this is indeed the correct address.

If you have questions please email me:

1.  put PSYC 3470 in your subject line
2.  email me at: mcrump\@brooklyn.cuny.edu

### General Help with Research and Writing

The Library maintains a collection of links to sites that can assist you with proper citation format and paraphrasing and quoting other authors at [Research & Writing Help](https://library.brooklyn.cuny.edu/resources/?service=research-help). The Learning Center has writing tutors available to help you with your writing <http://lc.brooklyn.cuny.edu/>.

The best learning is done in conversation with others, whether they are people---classmates, teachers, friends---or texts---books, articles, essays, poems, films etc. It should not be a solitary process. However, the assignments that you hand in for this course must be done on your own, should represent your own thinking, and should be original work that you have done for this particular course. A good way to balance these two seemingly contradictory approaches (collaborative learning and original individually-produced work) without knowingly---or, even unwittingly---resorting to plagiarism or other forms of academic misconduct is to learn and meticulously observe the rules for citing the work of others (this could be the great point your roommate made that you used in your paper, it could be a well-turned phrase from an academic essay, or it could be anything in between). It is your responsibility to learn what constitutes plagiarism and the correct rules for citing sources---read the information on the following website carefully: <http://www.brooklyn.cuny.edu/bc/policies/>. The bottom line is: passing off anyone's words or ideas as your own for any reason whatsoever is plagiarism.

## Violations of Academic integrity

It is the responsibility of each student to understand and act in accordance with the University's policy on Academic Integrity, described below.

### University's policy on Academic Integrity

The faculty and administration of Brooklyn College support an environment free from cheating and plagiarism. Each student is responsible for being aware of what constitutes cheating and plagiarism and for avoiding both. The complete text of the CUNY Academic Integrity Policy and the Brooklyn College procedure for implementing that policy can be found at [this site](http://www.brooklyn.cuny.edu/web/about/initiatives.php). If a faculty member suspects a violation of academic integrity and, upon investigation, confirms that violation, or if the student admits the violation, the faculty member MUST report the violation.

### FYI on cheating etc.

Remember, you are responsible for not cheating or violating CUNY's [Academic Integrity Policy](http://www.cuny.edu/about/administration/offices/legal-affairs/policies-resources/academic-integrity-policy/). You are responsible for understanding that policy, and for conducting yourself in a manner such that you do not violate the policy.

The above link lists many examples of cheating and plagiarism that are not allowed. There are many more specific acts that you should NOT do. Here is an additional list of activities that will be sufficient cause for immediate failure in the course.

-   Do not take pictures of exam or quiz questions and share them with other students
-   Do not give other students answers during an exam or quiz, or any other assignment that is an individual assignment
-   Do not copy work from another source and submit it as your own
-   Do not copy and paste text from the internet and submit it as your own words
-   Do not copy and paste text and slightly alter wording to pass the work off as your own
-   Do not hire someone else to do the coursework for you
-   Do not copy and paste text into a paraphrasing app, and then submit the output of the paraphrasing app as your own work
-   Do not copy random words from the internet that have nothing to do with the assignment and submit them as your own work.
-   Do not work on individual assignments with other students, share answers or other material, and then all hand in versions of the same thing that are slightly different.
-   Do not plagiarize yourself by submitting work that you have previously completed in another class.

### Mandate to report violations

If a faculty member suspects a violation of academic integrity and, upon investigation, confirms that violation, or if the student admits the violation, the faculty member MUST report the violation. Students should be aware that faculty may use plagiarism detection software.

There is no excuse for cheating. Students who are caught cheating may receive a failing grade for the entire course. All students who violate the academic integrity will receive a Faculty Action Report, which will go on their personal file at the Academic Integrity Office.

## FAQ

If you have questions about the syllabus, let's talk about it in class, and/or please create a thread to discuss the question on the discussion board for this course on Blackboard.
