---
title: "14 More Tidy Tuesday"
author: "Matt Crump"
date: "1/23/2023"
order: 14
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Read

There are no textbook readings. 

We will be using class time to discuss issues with your final projects, and to continue practicing data-visualization by completing tidy tuesday challenges, which involve obtaining open data and visualizing patterns from the open data set. 

## Additional resources

See the general assignment information about tidy tuesday.

<https://crumplab.com/psyc3470/modules/General%20Assignments/>


## Week 14 assignment

1. Here are a few blogging options. If you want to go in another direction to hone your data-visualization skills, that is OK too.

A. Blog about the tidy tuesday examples that we discuss in class
B. Use the time to complete a missing blog post
C. Blog about completing an aspect of your final project
D. Blog about a different tidy tuesday challenge that we did not discuss in class (if you do this, you will get credit both for this week's blog and for completing a tidy tuesday challenge)
