---
title: "9 Practice Report"
author: "Matt Crump"
date: "1/23/2023"
order: 9
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Read

Read the chapter.

<https://psyteachr.github.io/ads-v2/06-formative.html>

## Goals and additional resources

In this exercise you receive a sample dataset, and you receive a finished reproducible report showing visualizations of the data. Your task is to reproduce the report using the skills you have learned in this class.

The data and example report are available in section 6.3 of the textbook. We have been completing this assignment in class, and there are examples in the course blog.

## Week 9 assignment

1. Make a new blog post for this assignment. Obtain the data, and then attempt to reproduce the sample report. Your blog post should look as close to the example report as possible. 

Midterm replacement option and extra credit.

You can complete this assignment in place of part 2 of the midterm. If you complete both, then you get extra credit for part 2 of the midterm, as well as credit for this assignment.
